server:
  port: 8088
logging:
  level:
    org.springframework: DEBUG #??? ??? ? ?? ?? log??

spring:
  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: username
      password: password123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
management:
  endpoints:
    web:
      exposure:
        include: "*"

