server:
  port: 8088
logging:
  level:
    org.springframework: DEBUG #??? ??? ? ?? ?? log??

spring:
  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: username
      password: password123
management:
  endpoints:
    web:
      exposure:
        include: "*"

